### PR TITLE
Fix bot joining in AFK voice channels

### LINKED ISSUE #147: Bot will join AFK channel and 'play' music
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [x] Bug Report

### Description

I can request the bot to play music for me even when I am in the AFK channel of my server and obviously won't be able to hear anything. 

Me in AFK with the bot

This is not desired behavior as its pretty useless and prevents other people from using the bot. 

It would be better if the bot would not play music in designated AFK channels, and more generally, not play music in channels where it can't use voice at all.

### PR DESCRIPTION
**Pull request by MichailiK**
### This pull request...
  - [x] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
Since Discord automatically mutes users in AFK channels, bots shouldn't
play music inside AFK channels. This PR also fixes #147.
**This may be a controversial PR, since it takes away the freedom of using music commands in AFK channels.**

### Purpose
This prevents users from playing music in AFK channels, where all users are guild-muted.

### Relevant Issue(s)
This PR closes #147.

### CODE REVIEW

File: src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java [hunk 1]
```diff
@@ -68,7 +68,7 @@ protected void execute(CommandEvent event)
             if(current==null)
                 current = settings.getVoiceChannel(event.getGuild());
             GuildVoiceState userState = event.getMember().getVoiceState();
-            if(!userState.inVoiceChannel() || userState.isDeafened() || (current!=null && !userState.getChannel().equals(current)))
+            if(!userState.inVoiceChannel() || userState.isDeafened() || (current!=null && !userState.getChannel().equals(current)) || userState.getGuild().getAfkChannel().equals(userState.getChannel()))
```
Comment (MichailiK) [inline src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: CodeFactor seems to not like the complexity of the function after I added the AFK channel check in this if-statement

Comment (jagrosh) [reply src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: This probably shouldn't be a simple addition to this if-statement anyway, as the error message will be incorrect. As you've written this, if a user is in an AFK channel, the bot will reply "You must be listening in NameOfAFKChannel to use that!" instead of something along the lines of "You cannot use that while in an AFK channel!"

Comment (MichailiK) [reply src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: Alright, I wrote a message that's similar to [MusicCommand.java#L56](https://github.com/jagrosh/MusicBot/blob/master/src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java#L56)
> You cannot use that command in an AFK channel!

File: src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java [hunk 2]
```diff
@@ -73,6 +73,13 @@ protected void execute(CommandEvent event)
                 event.replyError("You must be listening in "+(current==null ? "a voice channel" : "**"+current.getName()+"**")+" to use that!");
                 return;
             }
+
+            if(userState.getGuild().getAfkChannel().equals(userState.getChannel()))
```
Comment (jagrosh) [inline src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: I think this will NPE if no afk channel is set

Comment (Sanduhr32) [reply src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]:
```suggestion
VoiceChannel afkChannel = userState.getGuild().getAfkChannel();
if(afkChannel != null && afkChannel.equals(userState.getChannel()))
```

Comment (MichailiK) [reply src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: Oh, right! Also, thank you @Sanduhr32, I've applied your suggestion.

Comment (Sanduhr32) [reply src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java]: The issue is just it didn't let me do indention. Would you please do that?

@jagrosh I suggest squash merging this pr.
